# Generated by Django 4.2.9 on 2024-10-26 23:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quota",
            name="validity_time",
        ),
        migrations.RemoveField(
            model_name="quota",
            name="validity_type",
        ),
        migrations.AlterField(
            model_name="plan",
            name="variant",
            field=models.CharField(
                choices=[
                    ("Bandwidth", "Bandwidth"),
                    ("Data", "Data"),
                    ("Time", "Time"),
                ],
                default="Data",
                max_length=16,
                verbose_name="Plan Variant:",
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Critical"),
                    (2, "High"),
                    (3, "Important"),
                    (4, "Medium"),
                    (5, "Low"),
                    (6, "Minor"),
                    (7, "Trivial"),
                ],
                default="4",
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="uptime_limit",
            field=models.DurationField(
                blank=True,
                default="30 00:00:00",
                help_text="'00:30:00' (30 minutes), '15 00:45:00' (15 days, 0 hours, 45 minutes, and 0 seconds), '0' (no expiration)",
                null=True,
            ),
        ),
    ]
