# Generated by Django 4.2.9 on 2024-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricing",
            name="period_type",
            field=models.CharField(
                choices=[
                    ("Fixed", "Fixed"),
                    ("Anniversary", "Anniversary"),
                    ("Accumulative", "Accumulative"),
                ],
                default="Anniversary",
                help_text="Fixed: expire at the end of month, Anniversary: expire 30 days from refill date, Accumulative: for rollover.",
                max_length=67,
                verbose_name="period type",
            ),
        ),
        migrations.AlterField(
            model_name="pricing",
            name="period",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                default=30,
                help_text="Type of plan period that could be purchased (e.g. 10 days, month, year, etc)",
                null=True,
                verbose_name="period",
            ),
        ),
    ]
