# Generated by Django 4.2 on 2024-05-31 22:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bandwidthsettings",
            options={
                "verbose_name": "Bandwidth Settings",
                "verbose_name_plural": "Bandwidth Settings",
            },
        ),
        migrations.RemoveField(
            model_name="billinginfo",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="billinginfo",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="order",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="planbandwidthsettings",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="planbandwidthsettings",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="planpricing",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="planpricing",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="planquota",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="planquota",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="pricing",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="quota",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="quota",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="recurringuserplan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="recurringuserplan",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="userplan",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="userplan",
            name="updated_by",
        ),
    ]
