# Generated by Django 4.2.9 on 2024-07-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0001_initial"),
        ("gmtisp_billing", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planpricing",
            name="has_automatic_renewal",
            field=models.BooleanField(
                default=False,
                help_text="Use automatic renewal if possible?",
                verbose_name="automatic renewal",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="plan",
            unique_together={("name", "organization")},
        ),
    ]
