# Generated by Django 4.2.9 on 2024-10-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0003_remove_quota_validity_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quota",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Optional link to page with more information (for clickable pricing table headers)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="uptime_limit",
            field=models.DurationField(
                blank=True,
                default="30 00:00:00",
                help_text="'00:30:00' (30 minutes), '15 00:45:00' (15 days, 0 hours, 45 minutes, and 0 seconds), 'Empty' (no expiration)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="userplan",
            name="start_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="start time"
            ),
        ),
    ]
