# Generated by Django 4.2.9 on 2024-07-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0003_alter_planpricing_has_automatic_renewal_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planpricing",
            name="visible",
            field=models.BooleanField(
                default=True,
                help_text="Is visible in current offer",
                verbose_name="visible",
            ),
        ),
    ]
