# Generated by Django 4.2.9 on 2024-11-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0004_quota_url_alter_quota_uptime_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="url",
            field=models.URLField(
                blank=True,
                help_text="Optional link to page with more information (for clickable plan table headers)",
            ),
        ),
        migrations.AlterField(
            model_name="quota",
            name="url",
            field=models.CharField(
                blank=True,
                help_text="Optional link to page with more information (for clickable quota table headers)",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="recurringuserplan",
            name="quota",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="Recurring quota",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.GMTISP_BILLING_QUOTA_MODEL,
            ),
        ),
    ]
