# Generated by Django 4.2.9 on 2024-07-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmtisp_billing', '0004_alter_planpricing_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpricing',
            name='has_automatic_renewal',
            field=models.BooleanField(default=False, help_text='Use automatic renewal if possible?', verbose_name='auto renewal'),
        ),
    ]
