# Generated by Django 4.2 on 2024-05-31 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0004_remove_bandwidthsettings_burst_rate_down_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planbandwidthsettings",
            name="bandwidth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.GMTISP_BILLING_BANDWIDTHSETTINGS_MODEL,
            ),
        ),
    ]
