# Generated by Django 4.2 on 2024-06-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gmtisp_billing", "0005_alter_planbandwidthsettings_bandwidth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="planbandwidthsettings",
            name="burst_threshold_down",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Burst threshold down",
            ),
        ),
        migrations.AlterField(
            model_name="planbandwidthsettings",
            name="burst_time_down",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Burst time down"
            ),
        ),
    ]
