# Generated by Django 4.2 on 2024-02-07 02:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import openwisp_users.mixins


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.OPENWISP_RADIUS_RADIUSGROUP_MODEL),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("openwisp_users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanQuota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("value", models.BigIntegerField(blank=True, default=1, null=True)),
            ],
            options={
                "verbose_name": "Plan quota",
                "verbose_name_plural": "Plans quotas",
                "abstract": False,
                "swappable": "PLANS_PLANQUOTA_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Pricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "period",
                    models.PositiveIntegerField(
                        blank=True,
                        db_index=True,
                        default=30,
                        null=True,
                        verbose_name="period",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to page with more information (for clickable pricing table headers)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pricing",
                "verbose_name_plural": "Pricings",
                "ordering": ("period",),
                "abstract": False,
                "swappable": "PLANS_PRICING_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "codename",
                    models.CharField(
                        db_index=True,
                        max_length=50,
                        unique=True,
                        verbose_name="codename",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=100, verbose_name="unit"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "is_boolean",
                    models.BooleanField(default=False, verbose_name="is boolean"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        help_text="Optional link to page with more information (for clickable pricing table headers)",
                        max_length=200,
                    ),
                ),
            ],
            options={
                "verbose_name": "Quota",
                "verbose_name_plural": "Quotas",
                "ordering": ("order",),
                "abstract": False,
                "swappable": "PLANS_QUOTA_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        db_index=True, editable=False, verbose_name="order"
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="description"),
                ),
                (
                    "available",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is still available for purchase",
                        verbose_name="available",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Is visible in current offer",
                        verbose_name="visible",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="Optional link to page with more information (for clickable pricing table headers)",
                    ),
                ),
                (
                    "default",
                    models.BooleanField(
                        blank=True,
                        default=None,
                        help_text='Both "Unknown" and "No" means that the plan is not default',
                        null=True,
                    ),
                ),
                (
                    "structure",
                    models.CharField(
                        choices=[
                            ("standalone", "Stand-alone plan"),
                            ("parent", "Parent plan"),
                            ("child", "Child plan"),
                        ],
                        default="standalone",
                        max_length=16,
                        verbose_name="Plan structure",
                    ),
                ),
                (
                    "plan_class",
                    models.CharField(
                        choices=[("Bandwidth", "Bandwidth"), ("Data", "Data")],
                        default="Data",
                        max_length=16,
                        verbose_name="Plan Class",
                    ),
                ),
                (
                    "type_of",
                    models.CharField(
                        choices=[("Prepaid", "Prepaid"), ("Postpaid", "Postpaid")],
                        default="Prepaid",
                        max_length=16,
                        verbose_name="Plan Type",
                    ),
                ),
                (
                    "recrurring",
                    models.BooleanField(
                        default=True,
                        help_text="This flag indicates if this plan is recrurring",
                        verbose_name="Plan Recrurring",
                    ),
                ),
                (
                    "recrurring_period",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                            ("Quarterly", "Quarterly"),
                            ("Semi-Yearly", "Semi-Yearly"),
                            ("Yearly", "Yearly"),
                            ("No Expiry", "No Expiry"),
                        ],
                        default="Monthly",
                        max_length=16,
                        verbose_name="Plan Recrurring Period",
                    ),
                ),
                (
                    "schedule",
                    models.CharField(
                        choices=[("Fixed", "Fixed"), ("Anniversary", "Anniversary")],
                        default="Anniversary",
                        help_text="Choose if period should be at the end of each Month, or 30 days period",
                        max_length=16,
                        verbose_name="Plan Recrurring Schedule",
                    ),
                ),
                (
                    "is_rollover",
                    models.BooleanField(
                        default=True,
                        help_text="New data will be added to the remaining data of the current subscription",
                        verbose_name="Data rollover",
                    ),
                ),
                (
                    "is_invoice_required",
                    models.BooleanField(
                        default=True,
                        help_text="If this flag is enabled, it means invoice will be created for this plan.",
                        verbose_name="Requires Invoice",
                    ),
                ),
                (
                    "is_payment_required",
                    models.BooleanField(
                        default=True,
                        help_text="If this flag is enabled, it means that a user that signs up with this plan is required to perform a payment.",
                        verbose_name="Requires payment",
                    ),
                ),
                (
                    "plan_cost",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Plan Cost",
                    ),
                ),
                (
                    "plan_setup_cost",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Plan Setup Cost",
                    ),
                ),
                (
                    "plan_tax",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Plan Tax",
                    ),
                ),
                (
                    "plan_currency",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        null=True,
                        verbose_name="Plan Currency",
                    ),
                ),
                (
                    "rating",
                    models.FloatField(editable=False, null=True, verbose_name="Rating"),
                ),
                (
                    "customized",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="customized",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="openwisp_users.organization",
                        verbose_name="organization",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Only choose a parent plan if you're creating a child plan.  For example if this is a size 4 of a particular t-shirt.  Leave blank if this is a stand-alone plan (i.e. there is only one version of this plan).",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="plans.plan",
                        verbose_name="Parent plan",
                    ),
                ),
                (
                    "quotas",
                    models.ManyToManyField(
                        through="plans.PlanQuota", to=settings.PLANS_QUOTA_MODEL
                    ),
                ),
                (
                    "radius_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_radius",
                        to=settings.OPENWISP_RADIUS_RADIUSGROUP_MODEL,
                        verbose_name="RADIUS group:",
                    ),
                ),
                (
                    "temp_radius_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_temp_radius",
                        to=settings.OPENWISP_RADIUS_RADIUSGROUP_MODEL,
                        verbose_name="Temporary RADIUS group:",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan",
                "verbose_name_plural": "Plans",
                "ordering": ("order",),
                "abstract": False,
            },
            bases=(openwisp_users.mixins.ValidateOrgMixin, models.Model),
        ),
        migrations.CreateModel(
            name="BandwidthSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Bandwidth determines how much traffic can pass through,5 Mbps, means, user on this plan can transmit data up to a capacity/speed 5 Mbps",
                        max_length=32,
                        null=True,
                        verbose_name="Bandwidth Name",
                    ),
                ),
                (
                    "bandwidth_up",
                    models.CharField(
                        blank=True, max_length=8, null=True, verbose_name="Bandwidth Up"
                    ),
                ),
                (
                    "bandwidth_down",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="Bandwidth Down",
                    ),
                ),
                (
                    "traffic_unit",
                    models.CharField(
                        choices=[
                            ("Megabyte (MB)", "Megabyte (MB)"),
                            ("Gigabyte (GB)", "Gigabyte (GB)"),
                            ("Terabyte (TB)", "Terabyte (TB)"),
                        ],
                        default="Gigabyte (GB)",
                        max_length=16,
                        verbose_name="Plan Unit",
                    ),
                ),
                (
                    "traffic_total",
                    models.CharField(
                        blank=True,
                        help_text="The total traffic/data allowed to use",
                        max_length=32,
                        null=True,
                        verbose_name="Traffic Total",
                    ),
                ),
                (
                    "plan_refill_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="Plan Refill Cost",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        max_length=32,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bandwidth_for_plan",
                        to="plans.plan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bandwidth Settings",
                "verbose_name_plural": "Bandwidth Settings",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "expire",
                    models.DateField(
                        blank=True,
                        db_index=True,
                        default=None,
                        null=True,
                        verbose_name="expire",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="active"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="plans.plan",
                        verbose_name="plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "User plan",
                "verbose_name_plural": "Users plans",
                "abstract": False,
                "swappable": "PLANS_USERPLAN_MODEL",
            },
        ),
        migrations.CreateModel(
            name="RecurringUserPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Token, that will be used for payment renewal. Depends on used payment provider",
                        max_length=255,
                        null=True,
                        verbose_name="recurring token",
                    ),
                ),
                (
                    "payment_provider",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Provider, that will be used for payment renewal",
                        max_length=255,
                        null=True,
                        verbose_name="payment provider",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=7,
                        null=True,
                        verbose_name="amount",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="tax",
                    ),
                ),
                ("currency", models.CharField(max_length=3, verbose_name="currency")),
                (
                    "has_automatic_renewal",
                    models.BooleanField(
                        default=False,
                        help_text="Automatic renewal is enabled for associated plan. If False, the plan renewal can be still initiated by user.",
                        verbose_name="has automatic plan renewal",
                    ),
                ),
                (
                    "token_verified",
                    models.BooleanField(
                        default=False,
                        help_text="The recurring token has been verified by at least one payment to be working.",
                        verbose_name="token has been verified by payment",
                    ),
                ),
                ("card_expire_year", models.IntegerField(blank=True, null=True)),
                ("card_expire_month", models.IntegerField(blank=True, null=True)),
                (
                    "card_masked_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        help_text="Recurring pricing",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PLANS_PRICING_MODEL,
                    ),
                ),
                (
                    "user_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring",
                        to=settings.PLANS_USERPLAN_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "swappable": "PLANS_RECURRINGUSERPLAN_MODEL",
            },
        ),
        migrations.AddField(
            model_name="planquota",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
            ),
        ),
        migrations.AddField(
            model_name="planquota",
            name="quota",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.PLANS_QUOTA_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PlanPricing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "price",
                    models.DecimalField(db_index=True, decimal_places=2, max_digits=7),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "has_automatic_renewal",
                    models.BooleanField(
                        default=False,
                        help_text="Use automatic renewal if possible?",
                        verbose_name="has automatic renewal",
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(
                        default=True,
                        help_text="Is visible in current offer",
                        verbose_name="is visible by default",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="plans.plan"
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PLANS_PRICING_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan pricing",
                "verbose_name_plural": "Plans pricings",
                "ordering": ("order", "pricing__period"),
                "abstract": False,
                "swappable": "PLANS_PLANPRICING_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("flat_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "completed",
                    models.DateTimeField(
                        blank=True, db_index=True, null=True, verbose_name="completed"
                    ),
                ),
                (
                    "plan_extended_from",
                    models.DateField(
                        blank=True,
                        help_text="The plan was extended from this date",
                        null=True,
                        verbose_name="plan extended from",
                    ),
                ),
                (
                    "plan_extended_until",
                    models.DateField(
                        blank=True,
                        help_text="The plan was extended until this date",
                        null=True,
                        verbose_name="plan extended until",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=2,
                        max_digits=7,
                        verbose_name="amount",
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                        verbose_name="tax",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="EUR", max_length=3, verbose_name="currency"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "new"),
                            (2, "completed"),
                            (3, "not valid"),
                            (4, "canceled"),
                            (5, "returned"),
                        ],
                        default=1,
                        verbose_name="status",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_order",
                        to="plans.plan",
                        verbose_name="plan",
                    ),
                ),
                (
                    "pricing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PLANS_PRICING_MODEL,
                        verbose_name="pricing",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ("-created",),
                "abstract": False,
                "swappable": "PLANS_ORDER_MODEL",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("number", models.IntegerField(db_index=True)),
                ("full_number", models.CharField(max_length=200)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Invoice"),
                            (2, "Invoice Duplicate"),
                            (3, "Order confirmation"),
                        ],
                        db_index=True,
                        default=1,
                    ),
                ),
                ("issued", models.DateField(db_index=True)),
                (
                    "issued_duplicate",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                (
                    "selling_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("payment_date", models.DateField(db_index=True)),
                ("unit_price_net", models.DecimalField(decimal_places=2, max_digits=7)),
                ("quantity", models.IntegerField(default=1)),
                ("total_net", models.DecimalField(decimal_places=2, max_digits=7)),
                ("total", models.DecimalField(decimal_places=2, max_digits=7)),
                ("tax_total", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "tax",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=2,
                        max_digits=4,
                        null=True,
                    ),
                ),
                (
                    "rebate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=4
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                ("item_description", models.CharField(max_length=200)),
                (
                    "buyer_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Name"),
                ),
                (
                    "buyer_street",
                    models.CharField(blank=True, max_length=200, verbose_name="Street"),
                ),
                (
                    "buyer_zipcode",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Zip code"
                    ),
                ),
                (
                    "buyer_city",
                    models.CharField(blank=True, max_length=200, verbose_name="City"),
                ),
                (
                    "buyer_country",
                    django_countries.fields.CountryField(
                        blank=True, default="PL", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "buyer_tax_number",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="TAX/VAT number"
                    ),
                ),
                (
                    "shipping_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Name"),
                ),
                (
                    "shipping_street",
                    models.CharField(blank=True, max_length=200, verbose_name="Street"),
                ),
                (
                    "shipping_zipcode",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Zip code"
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(blank=True, max_length=200, verbose_name="City"),
                ),
                (
                    "shipping_country",
                    django_countries.fields.CountryField(
                        blank=True, default="PL", max_length=2, verbose_name="Country"
                    ),
                ),
                ("require_shipment", models.BooleanField(db_index=True, default=False)),
                ("issuer_name", models.CharField(max_length=200, verbose_name="Name")),
                (
                    "issuer_street",
                    models.CharField(max_length=200, verbose_name="Street"),
                ),
                (
                    "issuer_zipcode",
                    models.CharField(max_length=200, verbose_name="Zip code"),
                ),
                ("issuer_city", models.CharField(max_length=200, verbose_name="City")),
                (
                    "issuer_country",
                    django_countries.fields.CountryField(
                        default="PL", max_length=2, verbose_name="Country"
                    ),
                ),
                (
                    "issuer_tax_number",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="TAX/VAT number"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.PLANS_ORDER_MODEL,
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "abstract": False,
                "swappable": "PLANS_INVOICE_MODEL",
            },
        ),
        migrations.CreateModel(
            name="BillingInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        null=True,
                        verbose_name="created",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "tax_number",
                    models.CharField(
                        blank=True, db_index=True, max_length=200, verbose_name="VAT ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True, max_length=200, verbose_name="name"
                    ),
                ),
                ("street", models.CharField(max_length=200, verbose_name="street")),
                ("zipcode", models.CharField(max_length=200, verbose_name="zip code")),
                ("city", models.CharField(max_length=200, verbose_name="city")),
                (
                    "country",
                    django_countries.fields.CountryField(
                        max_length=2, verbose_name="country"
                    ),
                ),
                (
                    "shipping_name",
                    models.CharField(
                        blank=True,
                        help_text="optional",
                        max_length=200,
                        verbose_name="name (shipping)",
                    ),
                ),
                (
                    "shipping_street",
                    models.CharField(
                        blank=True,
                        help_text="optional",
                        max_length=200,
                        verbose_name="street (shipping)",
                    ),
                ),
                (
                    "shipping_zipcode",
                    models.CharField(
                        blank=True,
                        help_text="optional",
                        max_length=200,
                        verbose_name="zip code (shipping)",
                    ),
                ),
                (
                    "shipping_city",
                    models.CharField(
                        blank=True,
                        help_text="optional",
                        max_length=200,
                        verbose_name="city (shipping)",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Billing info",
                "verbose_name_plural": "Billing infos",
                "abstract": False,
                "swappable": "PLANS_BILLINGINFO_MODEL",
            },
        ),
    ]
