# Generated by Django 4.2 on 2024-02-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("plans", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bandwidthsettings",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="Bandwidth determines how much traffic can pass through, 5 Mbps, means, user on this plan can transmit data up to a capacity/speed 5 Mbps",
                max_length=32,
                null=True,
                verbose_name="Bandwidth Name",
            ),
        ),
    ]
