# Generated by Django 4.2 on 2024-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("testing_app", "0007_radiusaccounting_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operator",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
