# Generated by Django 4.2 on 2024-02-08 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("testing_app", "0008_alter_operator_id_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationRadiusSettings",
        ),
        migrations.DeleteModel(
            name="RadiusAccounting",
        ),
    ]
