# Generated by Django 4.2 on 2024-05-15 06:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("testing_app", "0009_delete_organizationradiussettings_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
