# Generated by Django 4.2.9 on 2024-10-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="session_quota",
            field=models.PositiveIntegerField(default=0, verbose_name="session quota"),
        ),
    ]
