# Generated by Django 4.2.9 on 2024-08-19 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, unique=True, verbose_name="email"
            ),
        ),
    ]
