# Generated by Django 4.2.9 on 2024-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_users", "0002_organization_session_quota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="session_quota",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of concurrent sessions allowed",
                verbose_name="session quota",
            ),
        ),
    ]
