# Generated by Django 4.2.9 on 2024-07-18 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_radius", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registereduser",
            name="method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Unspecified"),
                    ("manual", "Manually created"),
                    ("email", "Email (No Identity Verification)"),
                    ("mobile_phone", "Mobile phone verification"),
                    ("social_login", "Social login"),
                    ("saml", "Single Sign-On (SAML)"),
                ],
                default="",
                help_text="users can sign up in different ways, some methods are valid as indirect identity verification (eg: mobile phone SIM card in most countries)",
                max_length=64,
                verbose_name="registration method",
            ),
        ),
    ]
