# Generated by Django 5.1.3 on 2024-11-17 11:29

import openwisp_radius.base.validators
import openwisp_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openwisp_radius', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='allowed_mobile_prefixes',
            field=openwisp_utils.fields.FallbackTextField(blank=True, default=None, fallback='+44,+39,+237,+595,+233', help_text='Comma separated list of international mobile prefixes allowed to register via the user registration API.', null=True),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='freeradius_allowed_hosts',
            field=openwisp_utils.fields.FallbackTextField(blank=True, default=None, fallback='127.0.0.1,localhost', help_text='Comma separated list of IP addresses allowed to access freeradius API', null=True),
        ),
        migrations.AlterField(
            model_name='organizationradiussettings',
            name='password_reset_url',
            field=openwisp_utils.fields.FallbackCharField(blank=True, default=None, fallback='http://localhost:8080/{organization}/password/reset/confirm/{uid}/{token}', help_text='Enter the URL where users can reset their password', max_length=200, null=True, validators=[openwisp_radius.base.validators.password_reset_url_validator], verbose_name='Password reset URL'),
        ),
        migrations.AlterField(
            model_name='registereduser',
            name='method',
            field=models.CharField(blank=True, choices=[('', 'Unspecified'), ('manual', 'Manually created'), ('email', 'Email'), ('mobile_phone', 'Mobile phone')], default='', help_text='users can sign up in different ways, some methods are valid as indirect identity verification (eg: mobile phone SIM card in most countries)', max_length=64, verbose_name='registration method'),
        ),
    ]
