# Generated by Django 4.2.9 on 2024-11-16 13:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_radius", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nas",
            name="gps_loc",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="GPS location"
            ),
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="whether the user has completed any identity verification process successfully",
                verbose_name="verified",
            ),
        ),
    ]
