# Generated by Django 4.2.9 on 2024-11-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("openwisp_radius", "0003_nas_gps_loc_alter_registereduser_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nas",
            name="gps_loc",
        ),
        migrations.AlterField(
            model_name="registereduser",
            name="is_verified",
            field=models.BooleanField(
                default=False,
                help_text="whether the user has completed any identity verification process sucessfully",
                verbose_name="verified",
            ),
        ),
    ]
